name: apache

on:
  schedule:
    - cron:  "0 */48 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.8.0
        with:
          context: apache
          push: true
          tags: |
            ghcr.io/sundowndev/meganz-webclient:latest
            ghcr.io/sundowndev/meganz-webclient:apache
          platforms: linux/amd64 # ,linux/arm/v7,linux/arm64 - TODO(sundowndev): enable arm support

      - name: Display new image digest
        run: echo "${{ env.REGISTRY }}/sundowndev/meganz-webclient@${{ steps.docker_build.outputs.digest }}"
